version: "3.3"

services:
  php:
    image: fsilva/php:7.3
    ports:
    - 8080:80
    volumes:
    - ./:/var/www/app
    environment:
    - USE_XDEBUG=yes
    - WEBROOT=public

  database:
    image: mysql:5
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=project
    - MYSQL_USER=db_user
    - MYSQL_PASSWORD=secret