<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMnwnjdO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnwnjdO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMnwnjdO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMnwnjdO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMnwnjdO\App_KernelDevDebugContainer([
    'container.build_hash' => 'MnwnjdO',
    'container.build_id' => 'd937eee9',
    'container.build_time' => 1579643800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnwnjdO');
